### ISSUE TITLE
Bug: getSelectedDay() with default value returns wrong month

### ISSUE THREAD

**Issue by tomdaniel-it** [shrikanth7698/Collapsible-Calendar-View-Android#11]
When nothing has been selected yet, the method getSelectedDay() (in CollapsibleCalendar) will return a Day object created with the day, month & year from Calendar, but with month, a +1 is added. This is inconsistent since the normal value when something is selected does not do a +1.
Calendar.get(2) returns the month starting from 0 - 11. With the +1, it changes to 1-12.
So: when nothing in calendar has been clicked yet, day.getMonth() returns 4. When I then click on the day of today, that day gets selected. Then day.getMonth() prints out 3. (day == getSelectedDay())
Recommendation: 
In CollapsibleCalendar in getSelectedDay() change:
`return new Day(year, month + 1, day);`
to:
`return new Day(year, month, day);`

**Comment by JSBerrocoso** [comment]
Same issue. Is Solved in other lib version??
