### ISSUE TITLE
How to go today

### ISSUE THREAD

**Issue by doforward** [shrikanth7698/Collapsible-Calendar-View-Android#14]

**Comment by shrikanth7698** [comment]
can you be more clear please?

**Comment by doforward** [comment]
if i go nextMonth(), I want add a button click can go to today

**Comment by esmerlinep** [comment]
@doforward you can do that on this way: (made in kotlin )
 val day = collapsibleCalendar.selectedDay
val today= Day(day.year, day.month, collapsibleCalendar.todayItemPosition +1)
                    collapsibleCalendar.select(dia)
