### ISSUE TITLE
incompatibility with api 21

### ISSUE THREAD

**Issue by mamzii** [shrikanth7698/Collapsible-Calendar-View-Android#17]
Manifest merger failed : uses-sdk:minSdkVersion 17 cannot be smaller than version 21 declared in library [com.github.shrikanth7698:Collapsible-Calendar-View-Android:v1.0.0]

**Comment by nishchalraj** [comment]
Try to change the minimum SDK version.
The minSdkVersion in library is 21 and it can't be compatible with 17.
