### ISSUE TITLE
State Collapsed at first

### ISSUE THREAD

**Issue by rahul860366** [shrikanth7698/Collapsible-Calendar-View-Android#2]
I am setting  cal.setStateWithUpdateUI(UICalendar.STATE_COLLAPSED) during initialization, but it remains in expanded form itself.

**Comment by mayankzen123** [comment]
Use this 
` collapsibleCalendar.setState(UICalendar.STATE_COLLAPSED);`

**Comment by jialbanc** [comment]
@mayankzen123 I tried that, it didn't work
