### ISSUE TITLE
Event dot Color

### ISSUE THREAD

**Issue by lucasorso** [shrikanth7698/Collapsible-Calendar-View-Android#21]
Why in this release(1.0.0) cannot set dot color ?
While in master branch this functionality exists!

**Comment by AadarshaSadan** [comment]
not working

**Comment by shrikanth7698** [comment]
I have released a new build. 

`
implementation 'com.github.shrikanth7698:Collapsible-Calendar-View-Android:v1.0.3'
`

In this build you can set a constraint to disable the previous dates.  Please refer to the sample app.
