### ISSUE TITLE
Swipe Gestures not working

### ISSUE THREAD

**Issue by PritishSawant** [shrikanth7698/Collapsible-Calendar-View-Android#25]
Suppose if i collapse the calendar view and instead of pressing the buttons i want to change the dates by swiping. I am adding swipe gesture code to your com.shrikanthravi.collapsiblecalendarview.view.LockScrollView view but its not working. Let me know why

**Comment by vishalkumarsinghvi** [comment]
I am also facing the same problem

**Comment by tejaschavan21** [comment]
Hello @shrikanth7698 any update on this? 
I tried to change the return value of Touch Event overwritten methods in LockScrollView class enabling the onInterceptTouchEvent allows to add gesture to scroll between the weeks but disables the tap event for selecting date. Can you please suggest a quick solution to scroll between the weeks when calendar is collapsed

**Comment by karangoel16** [comment]
https://github.com/shrikanth7698/Collapsible-Calendar-View-Android/pull/48

**Comment by karangoel16** [comment]
have added the swipe events in the following branch

**Comment by shrikanth7698** [comment]
I have released a new build.  Thanks to @karangoel16 
Use this one.
`
implementation 'com.github.shrikanth7698:Collapsible-Calendar-View-Android:v1.0.3'
`
