### ISSUE TITLE
Locale and Translation

### ISSUE THREAD

**Issue by tatomarchioli** [shrikanth7698/Collapsible-Calendar-View-Android#26]
Reading the few docs and the code itself I couldn't find a way to translate the calendar strings, like the days of the week, and I really want to use this widget but my app is in Brazillian Portuguese. Is there any way to translate via api or do I have to do it myself with the source ? 

Thanks for your awesome widget.

**Comment by robsonbbs** [comment]
If someone need it yet, just put this strings in your own strings.xml file:

<string name="monday">SEG</string>
<string name="tuesday">TER</string>
<string name="wednesday">QUA</string>
<string name="thursday">QUI</string>
<string name="friday">SEX</string>
<string name="saturday">SAB</string>
<string name="sunday">DOM</string>

This will override library's strings!

**Comment by maulikdadhaniya** [comment]
> If someone need it yet, just put this strings in your own strings.xml file:
> 
> `<string name="monday">SEG</string>`
> `<string name="tuesday">TER</string>`
> `<string name="wednesday">QUA</string>`
> `<string name="thursday">QUI</string>`
> `<string name="friday">SEX</string>`
> `<string name="saturday">SAB</string>`
> `<string name="sunday">DOM</string>`
> 
> This will override library's strings!

Its's Work .. Thanks

**Comment by karangoel16** [comment]
https://github.com/shrikanth7698/Collapsible-Calendar-View-Android/pull/48
