### ISSUE TITLE
Disable a range of dates

### ISSUE THREAD

**Issue by margin555** [shrikanth7698/Collapsible-Calendar-View-Android#3]
How to Disable a range of dates in a month, like from 11 to 23. Is there any way to do that?

**Comment by shrikanth7698** [comment]
Hey, margin555 I'm currently working on that. Will include it in next release

**Comment by margin555** [comment]
thanks.

**Comment by EzequielMessore** [comment]
hey, is there some update about this caracteristic?

**Comment by shrikanth7698** [comment]
I have released a new build. 

`
implementation 'com.github.shrikanth7698:Collapsible-Calendar-View-Android:v1.0.3'
`

In this build you can set a constraint to disable the previous dates.  Please refer to the sample app.
