### ISSUE TITLE
unable to run sample

### ISSUE THREAD

**Issue by dineshkandan1990** [shrikanth7698/Collapsible-Calendar-View-Android#39]
Binary XML file line #8: Binary XML file line #8: Error inflating class com.shrikanthravi.collapsiblecalendarview.widget.CollapsibleCalendar

**Comment by jayellos** [comment]
Same here, I can't run the sample app in master branch.

**Comment by jayellos** [comment]
Here's the fix [PR 41](https://github.com/shrikanth7698/Collapsible-Calendar-View-Android/pull/41)
