### ISSUE TITLE
on Button click change date next and previous 

### ISSUE THREAD

**Issue by Yagnesh123456** [shrikanth7698/Collapsible-Calendar-View-Android#42]
on Button click change date next and previous 
now we can click on date get selected date but i want my custom button perform next and previous date  how to get programmatically date next and previous    
on next button click get Tomorrows date and click on previous button gets yesterdays date

like today date 04-05-2019 so now click on next button click get date 05-05-2019 or click on previous button click get date 03-05-2019  

 this next and previous button is my Button widgets button 

Thank you in advance and sorry for my English

**Comment by tejaschavan21** [comment]
@Yagnesh123456 if You just want to shift the date to prev and next to current(today's) date then you can call/use CollapsableCalendar.select(Day day) method where you can send next day or previous day date. Here Day is nothing but a model class, while initialising you can send (year, month, day) to constructor.
