### ISSUE TITLE
how to disable past days ??

### ISSUE THREAD

**Issue by libin12** [shrikanth7698/Collapsible-Calendar-View-Android#46]
i want to disable past days

**Comment by karangoel16** [comment]
Check my repo, have been working on something like this

**Comment by shrikanth7698** [comment]
I have released a new build.  Thanks to @karangoel16 

`
implementation 'com.github.shrikanth7698:Collapsible-Calendar-View-Android:v1.0.3'
`

In this build you can set a constraint to disable the previous dates.  Please refer to the sample app.
