### ISSUE TITLE
NO Method to Set MinDate like Datepicker.

### ISSUE THREAD

**Issue by krunal8055** [shrikanth7698/Collapsible-Calendar-View-Android#56]
I wanted to set min date like datepicker. Min date is  to just set current date in calender. so after today's date user can choose any date but not before today's date.

**Comment by shrikanth7698** [comment]
I have released a new build. 

`
implementation 'com.github.shrikanth7698:Collapsible-Calendar-View-Android:v1.0.3'
`

In this build you can set a constraint to disable the previous dates.  Please refer to the  sample app.
