### ISSUE TITLE
Minimum SDK Requirement

### ISSUE THREAD

**Issue by suhafer** [shrikanth7698/Collapsible-Calendar-View-Android#6]
Hi,
is it okay to use this library when i set my apps min sdk version to 18?

thanks.

**Comment by shrikanth7698** [comment]
Yeah... It will work

**Comment by suhafer** [comment]
Okay thanks.

**Comment by firecatmusic** [comment]
Manifest merger failed : uses-sdk:minSdkVersion 19 cannot be smaller than version 21 declared in library [com.github.shrikanth7698:Collapsible-Calendar-View-Android:v1.0.0] C:\Users\ThinkPad X240\.gradle\caches\transforms-1\files-1.1\Collapsible-Calendar-View-Android-v1.0.0.aar\1876086cb3b6b63b0e0827158e50ecbf\AndroidManifest.xml as the library might be using APIs not available in 19
	Suggestion: use a compatible library with a minSdk of at most 19,
		or increase this project's minSdk version to at least 21,
		or use tools:overrideLibrary="com.shrikanthravi.collapsiblecalendarview" to force usage (may lead to runtime failures)
