### ISSUE TITLE
When using collapse function the days numbers doesn't show

### ISSUE THREAD

**Issue by Ahmed-Abdelmeged** [shrikanth7698/Collapsible-Calendar-View-Android#7]
When i call collapsibleCalendarView.collapse(0)
It hide the the days number like this
![image](https://user-images.githubusercontent.com/26193205/38776918-4b74696c-409f-11e8-840d-be79cb19b801.png)

But i want it like normal collapse like the one if i press the button
![image](https://user-images.githubusercontent.com/26193205/38776931-8d981d34-409f-11e8-97f1-c7cb1c1d81eb.png)

**Comment by shrikanth7698** [comment]
Hey Ahmed, I solved this issue. I am gonna release a new version by tonight. Please use the new version. Thanks

**Comment by Ahmed-Abdelmeged** [comment]
OK another thing also if you can fix will be great.
when call collapsibleCalendarView.selectedDay if the user doesn't selected a day it should return the current day not crash because  getSelectedItem = null

**Comment by shrikanth7698** [comment]
Hey Ahmed, Thanks for pointing this out. I fixed this issue.

**Comment by Ahmed-Abdelmeged** [comment]
Thank you and don't forget the Parcelable :D

**Comment by shrikanth7698** [comment]
<img width="1440" alt="screen shot 2018-04-15 at 7 11 57 pm" src="https://user-images.githubusercontent.com/25195315/38779077-fde41d5e-40e0-11e8-8115-253b1d1ff9dd.png">

Hey Ahmed, This is what you asked for right?

**Comment by shrikanth7698** [comment]
Hey, Ahmed sorry I made a small mistake. I used stringArray instead of intArray.
I fixed it now.

**Comment by Ahmed-Abdelmeged** [comment]
Yes i think so.

**Comment by shrikanth7698** [comment]
I released the new Version.
Go check it out.
And Thank you so much for pointing out this issues!
